import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbConfig } from "@/utils/dbConfig";
import Header from "./components/Header";
import MainLayout from "./MainLayout";
import { GlobalContext } from "./global/GlobalContext";
import Provider from "./components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConfig();
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContext>
          <Provider>
            <MainLayout children={children} />
          </Provider>
        </GlobalContext>
      </body>
    </html>
  );
}
