import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sider from "./components/Sider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex ">
          <div className="fixed">
            <Sider />
          </div>

          <div className="w-full flex justify-end">
            <div className="flex w-[calc(100vw-285px)] p-4 border rounded-md my-4 mx-2 min-h-[97vh]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
